[package]
name = "lnd-rust"
version = "0.1.0"
authors = ["BitfuryLightning <lightning@bitfury.com>"]

[dependencies]
protobuf        = "1.*"
futures         = "0.*"
futures-cpupool = "0.1.*"
tls-api         = "0.*"
httpbis         = "0.4.1"
grpc = "0.2.1"
tls-api-native-tls = "0.1.1"

[build-dependencies]
protoc-rust-grpc = "0.2.1"



